server:
    port: 9999

spring:
    h2:
        console:
            enabled: true
            path: /h2-console

    datasource:
        url: jdbc:h2:mem:stockPredict;NON_KEYWORDS=USER
        username: sa
        password:
        driver-class-name: org.h2.Driver

app:
    upload:
        dir: uploadedFiles